services:
  keycloak:
    container_name: keycloak-pharmacy
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5433/keycloak_db
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    networks:
      - common-network
    command:
      - "start-dev"
networks:
  common-network:
    driver: bridge

volumes:
  keycloak:
    driver: local