services:
#  pharmacy_db:
#    image: postgres:latest
#    container_name: pharmacy_db
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: pharmacy_db
#    volumes:
#      - pharmacy_db_data:/var/lib/postgresql/data
#      - ./sql:/docker-entrypoint-initdb.d #enabled to init table
#    ports:
#      - "5432:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U admin -d pharmacy_db" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - common-network
#  keycloak_db:
#    image: postgres:latest
#    container_name: keycloak_db
#    environment:
#      POSTGRES_USER: admin
#      POSTGRES_PASSWORD: admin
#      POSTGRES_DB: keycloak_db
#    volumes:
#      - keycloak_db_data:/var/lib/postgresql/data
#    ports:
#      - "5433:5432"
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -U admin -d keycloak_db" ]
#      interval: 10s
#      timeout: 5s
#      retries: 5
#    networks:
#      - common-network
  keycloak:
    container_name: keycloak-pharmacy
    image: quay.io/keycloak/keycloak:24.0.2
    ports:
      - "9090:8080"
#    depends_on:
#      keycloak_db:
#        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://13.215.191.215:5432/keycloakdb
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
    networks:
      - common-network
    command:
      - "start-dev"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health/live || exit 1" ]
      interval: 30s
      timeout: 15s
      retries: 10
      start_period: 60s

networks:
  common-network:
    driver: bridge

volumes:
  keycloak_db_data:
  pharmacy_db_data: