@startuml
autonumber

actor Employee as "Employee"
participant Backend as "Backend Service"
database Keycloak as "Identity Provider"

== Change Password Flow ==
Employee -> Backend: Request to change password (old & new)
Backend -> Keycloak: Check if old password is correct by get token
Keycloak -> Backend: return token or not
alt Old password is invalid
    Backend -> Employee: Send error message (Old password is incorrect)
else Old password is valid
    Backend -> Backend: Check if new password matches confirmation
    alt New password confirmation fails
        Backend -> Employee: Send error message (New password confirmation failed)
    else New password confirmation successful
        Backend -> Keycloak: Update user password
        Keycloak -> Backend: Confirm password change
        Backend -> Employee: Send success message (Password changed successfully)
    end
end

@enduml
