@startuml
autonumber

actor Employee as "Employee"
participant Backend as "Backend Service"
database DB as "Database"

== Fetch Employee Flow ==
Employee -> Backend: Fetch employees request
Backend --> DB: select
DB -> Backend: list of employees
Backend -> Employee: list of employees
@enduml

