spring:
  datasource:
    url: "${DATABASE_URL:jdbc:postgresql://13.215.191.215:5432/postgres}"
    username: "${DATABASE_USER:postgres}"
    password: "${DATABASE_PASSWORD:postgres}"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/pharmacy-management

server:
  port: 8081