spring:
  application:
    name: pharmacy
  profiles:
    active: dev
  jackson:
    serialization:
      WRITE_BIGDECIMAL_AS_PLAIN: true

server:
  servlet:
    context-path: /pharmacy

keycloak:
  auth-server-url: "${KEY_CLOAK_AUTH_SERVER_URL:http://localhost:9090}"
  realm: pharmacy-management
  client-id: admin-cli
  # admin user should be assigned realm-management (manage-users)
  username: admin
  password: admin
  grant-type: password
