@startuml
autonumber

actor Admin as "Admin"
participant Backend as "Backend Service"
database DB as "Database"

== Customer Updating Flow ==
Admin -> Backend: Customer update request
Backend -> DB: Fetch customer by id
alt [customer not exists]
    DB -> Backend: not found
    Backend -> Admin: customer is not exist
else [customer exist]
    DB -> Backend: customer
    Backend -> Backend: map customer
    Backend -> DB: update
    DB -> Backend: updated
    Backend -> Admin: updated success
end
@enduml

